# Default variables for Mailu role
mailu_enable_admin: true
mailu_persistence_size: 500Mi
mailu_redis_size: 150Mi
mailu_clamav_size: 150Mi
mailu_storage_class: longhorn-single-replica
mailu_enable_clamav: false
mailu_enable_oletools: false
mailu_enable_tika: false
mailu_roundcube_password: "someStrongPassword"
mailu_secret_key: "someSecretKey"

mailu_chart_version: "2.6.3"
