- name: Install Mailu using Helm for enabled projects (public SMTP)
  kubernetes.core.helm:
    name: "mailu"
    chart_ref: mailu/mailu
    chart_version: "{{ mailu_chart_version }}"
    release_namespace: mailu
    values:
      hostnames: >-
        {{ self_saas_projects |
           selectattr('mailu.enabled', 'defined') |
           selectattr('mailu.enabled') |
           map(attribute='domain') |
           map('regex_replace', '^', 'mailu.') |
           list }}
      domain: "{{ mailu_main_domain }}"
      customization:
        website: "http://localhost:8083/"
      ingress:
        enabled: false
        className: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "{{ cert_issuer_name }}"
          traefik.ingress.kubernetes.io/service.serversscheme: "http"
        tls:
          - hosts:
              - mailu.{{ mailu_main_domain }}Add commentMore actions
            secretName: mailu-certificates
        tlsFlavorOverride: "cert"
      admin:
        enabled: true
      initialAccount:
        enabled: true
        username: "{{ mailu_admin_username }}"
        password: "{{ mailu_admin_password }}"
        domain: "{{ mailu_main_domain }}"
        mode: "update"
      persistence:
        enabled: true
        storageClass: "{{ mailu_storage_class }}"
        size: "{{ mailu_persistence_size }}"
      redis:
        master:
          persistence:
            enabled: true
            size: "{{ mailu_redis_size }}"
      clamav:
        enabled: "{{ mailu_enable_clamav | default(false) }}"
        persistence:
          enabled: true
          size: "{{ mailu_clamav_size }}"
      webmail:
        enabled: true
      global:
        database:
          roundcube:
            password: "{{ mailu_roundcube_password }}"
      secretKey: "{{ mailu_secret_key }}"
      front:
        hostPort:
          enabled: false
        externalService:
          enabled: true
          type: LoadBalancer
          externalTrafficPolicy: Local
          annotations:
            traefik.ingress.kubernetes.io/service.serversscheme: "http"
          nodePorts:
            imaps: 993
          ports:
            imaps: true
        extraEnvVars:
          - name: WEBMAIL_ADDRESS
            value: "mailu-webmail.mailu.svc.cluster.local:80"
    wait: true
    wait_timeout: "{{ helm_install_timeout }}"
  when: self_saas_projects | selectattr('mailu.enabled', 'defined') | selectattr('mailu.enabled') | list | length > 0
